#without cloud config
#server:
#  port: 8080
#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''
#  h2:
#    console:
#      enabled: true
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  config:
#    import:
#      - "accounts-qa.yml"
#      - "accounts-prod.yml"
#  profiles:
#    active:
#      - qa

build:
  version: 3.0

accounts:
  message: "Welcome to eazybank api"
  contactDetails:
    name: "Murat Yayla"
    email: "murat@eazybank.com"
  onCallSupport:
    - (555) 551 12 22
    - (555) 123 44 55