spring:
  application:
    name: "configserver"
  profiles:
    active: git
    #active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/muratyayla26/eazybytes-config"
          default-label: main
          timeout: 5
          force-pull: true
          clone-on-start: true
          #native:
          #search-locations: "file:///Users//muratyayla//IdeaProjects//udemy//config-cloud-file"
          #search-locations: "classpath:/config"

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

server:
  port: 8071