spring:
  application:
    name: "configserver"
  profiles:
    active: git
    #active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/muratyayla26/eazybytes-config"
          default-label: main
          timeout: 5
          force-pull: true
          clone-on-start: true
          #native:
          #search-locations: "file:///Users//muratyayla//IdeaProjects//udemy//config-cloud-file"
          #search-locations: "classpath:/config"
  # removed for time saving during learning also spring-cloud-starter-bus-amqp dependency removed
  #rabbitmq:
   # host: "localhost"
   # port: 5672
   # username: "guest"
   # password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

server:
  port: 8071